config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'reservations/new'
  get 'users/account', to: 'users#account'
  get 'users/profile', to: 'users#profile'
  root 'users#top'
  resources :users
  resources :rooms do
    collection do
      get 'search'
    end
  end
  resources :reservations do
    collection do
      post 'confirm'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :rev_checkin, :rev_checkout, presence: true
  validates :rev_headcount, presence: true, numericality: {greater_than_or_equal_to: 1}
  validate :endAfterStart
  validate :date_before_start
  
  def stay_duration
   stay_days = (rev_checkout - rev_checkin).to_i
  end

  def total_price
   total = stay_duration * room.room_fee * rev_headcount
  end

  private

  def date_before_start
    return if self.rev_checkin.blank?
    errors.add(:rev_checkin, "は今日以降のものを選択してください") if self.rev_checkin < Date.today
  end

  def endAfterStart
    return if rev_checkin.blank? || rev_checkout.blank?
    if rev_checkout <= rev_checkin
      errors.add(:rev_checkout, "はチェックイン日より後の日付としてください")
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def new
    @room = Room.find(params[:id])
    @reservation = @room.reservations.new
  end

  def create
    @reservation = @user.reservations.new(reservation_params)
    @reservation.user_id = current_user.id
    if @reservation.save
      flash[:notice] = "予約が完了しました。"
      redirect_to root_path
    else
      flash[:alert] = "予約の保存に失敗しました。"
      render :new
    end
  end

  def confirm
    @room = Room.find(params[:reservation][:room_id])
    @reservation = @room.reservations.new(reservation_params)
    @reservation.user_id = current_user.id

    if @reservation.invalid?
      render :new
    else
      @reservation.rev_lengthofstay = stay_duration
      @reservation.rev_finalbill = total_price
    end
  end

  def index
    @reservations = current_user.reservations
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  private

  def stay_duration
    rev_lengthofstay = (@reservation.rev_checkout - @reservation.rev_checkin).to_i
  end

  def total_price
    rev_finalbill = stay_duration * @room.room_fee * @reservation.rev_headcount
  end

  def reservation_params
    params.require(:reservation).permit(:rev_checkin, :rev_checkout, :created_at, :rev_finalbill, :rev_headcount, :room_id, :user_id )
  end

  def set_user
    @user = current_user
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/confirm.html.erb
<h3>予約内容の確認</h3>

<%= form_with model: @reservation do |reservation| %>
  <table>
    <tr>
      <th>チェックイン</th>
      <td><%= reservation.date_field :rev_checkin, readonly: true %></td>
    </tr>
    <tr>
      <th>チェックアウト</th>
      <td><%= reservation.date_field :rev_checkout,readonly: true %></td>
    </tr>
    <tr>
      <th>日数</td>
      <td><%= reservation.number_field :rev_lengthofstay, readonly: true %>日</td>
    </tr>
    <tr>
      <th>人数</th>
      <td><%= reservation.number_field :rev_headcount, readonly: true %>人</td>
    </tr>
    <tr>
      <th>お支払い総額</th>
      <td><%= reservation.number_field :rev_finalbill, readonly:true %>円</td>
    </tr>
    <%= reservation.hidden_field :room_id %>
    <%= reservation.hidden_field :user_id %>
  </table>
    <%= reservation.submit "予約を確定" %>
<% end %>

app/views/reservations/index.html.erb
<h3>予約一覧</h3>
<p>全<%= @reservations.count %>件</p>

<table>
  <thead>
    <tr>
      <th>画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>合計料金</th>
      <th>チェックイン</th>
      <th>チェックアウト</th>
      <th>予約確定日時</th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td>
        <% if reservation.room.room_image.present? %>
          <%= image_tag @room.room_image.url %>
        <% else %>
          <%= image_tag("default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png")%>
        <% end %>
        </td>
        <td><%= link_to reservation.room.room_name, room_path(reservation.room_id) %></td>
        <td><%= reservation.room.room_introduction %></td>
        <td>¥<%= reservation.total_price %></td>
        <td><%= l reservation.rev_checkin, format: :short %></td>
        <td><%= l reservation.rev_checkout, format: :short %></td>
        <td><%= l reservation.created_at, format: :long %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/reservations/new.html.erb
<h2>予約する</h2>

<%= render "shared/error", obj: @reservation %>

<%= form_with(url: confirm_reservations_path, method: :post, model: [@room, @reservation], local: true) do |f| %>

  <div>
    <%= f.label :rev_checkin, "チェックイン日" %>
    <%= f.date_field :rev_checkin %>
  </div>
  <div>
    <%= f.label :rev_checkout, "チェックアウト日" %>
    <%= f.date_field :rev_checkout %>
  </div>
  <div>
    <%= f.label :rev_headcount, "人数" %>
    <%= f.text_field :rev_headcount %>人
  </div>
  <div>
    <%= f.submit "予約する" %>
  </div>
  <%= f.hidden_field :room_id %>
<% end %>