config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'reservations/new'
  get 'users/account', to: 'users#account'
  get 'users/profile', to: 'users#profile'
  root 'users#top'
  resources :users
  resources :rooms do
    collection do
      get 'search'
    end
  end
  resources :reservations do
    collection do
      post 'confirm'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  validates :room_name, presence: true
  validates :room_introduction, presence: true
  validates :room_fee, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :room_address, presence: true

  def self.search(search)
    return Room.all unless search
    Room.where('room_name LIKE(?)', "%#{search}%")
  end

  has_many :reservations
  belongs_to :user
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = Room.new
  end

  def show
    @room = Room.find(params[:id])
  end

  def search
    if params[:area].present?
      @rooms = Room.where("room_address LIKE ?", "%#{params[:area]}%")
    elsif params[:word].present?
      @rooms = Room.where("room_name LIKE ? OR room_introduction LIKE ?", "%#{params[:word]}%", "%#{params[:word]}%")
    end
  end

  def create
    @room = Room.new(params.require(:room).permit(:room_name, :room_introduction, :room_fee, :room_address))
    @room.user_id = current_user.id
    if @room.save
      flash[:notice] = "予約が完了しました。"
      redirect_to root_path
    else
      flash[:alert] = "予約の保存に失敗しました。"
      render :new
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<h2>登録済み一覧</h2>

<table>
  <thead>
    <tr>
      <th>施設画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>宿泊料金</th>
      <th>作成日</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td>
          <% if room.room_image.present? %>
            <%= image_tag room.room_image.url %>
          <% else %>
            <%= image_tag("default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png")%>
          <% end %>
        </td>
        <td><%= link_to room.room_name, room_path(room) %></td>
        <td><%= room.room_introduction %></td>
        <td>¥<%= room.room_fee %></td>
        <td><%= room.created_at.to_s(:datetime_jp) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/new.html.erb
<h2>施設登録</h2>

<%= render "shared/error", obj: @room %>

<%= form_with model: @room do |f| %>
  <table>
    <tr>
      <th><%= f.label :room_name, "施設名" %></th>
      <td><%= f.text_field :room_name %></td>
    </tr>
    <tr>
      <th><%= f.label :room_introduction, "施設詳細" %></th>
      <td><%= f.text_area :room_introduction %></td>
    </tr>
    <tr>
      <th><%= f.label :room_fee, "料金" %></th>
      <td><%= f.text_field :room_fee %>円</td>
    </tr>
    <tr>
      <th><%= f.label :room_address, "住所" %></th>
      <td><%= f.text_field :room_address %></td>
    </tr>
  </table>
  <div>
    <ul>
      <li><%= f.submit "登録完了する"%></li>
    </ul>
  </div>
<% end %>

app/views/rooms/search.html.erb
<%= form_with(url: search_rooms_path, method: :get, local: true) do |f| %>
  <%= f.text_field :area, placeholder: 'エリア名' %>
  <%= f.submit "検索", class: "btn btn-primary" %>
  <%= f.text_field :word, placeholder: 'キーワード' %>
  <%= f.submit "検索", class: "btn btn-primary" %>
<% end %>

<%= link_to '東京', '/rooms/search?area=東京&commit=検索' %>
<%= link_to '大阪', '/rooms/search?area=大阪&commit=検索' %>
<%= link_to '京都', '/rooms/search?area=京都&commit=検索' %>
<%= link_to '札幌', '/rooms/search?area=札幌&commit=検索' %>
<p>全<%= @rooms.present? ? @rooms.count : 0 %>件</p>


<% if params[:area].present? || params[:word].present? %>
  <table>
    <thead>
      <tr>
        <th>施設名</th>
        <th>住所</th>
        <th>施設紹介</th>
        <th>宿泊料金</th>
      </tr>
    </thead>

    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td><%= room.room_name %></td>
          <td><%= room.room_address %></td>
          <td><%= room.room_introduction %></td>
          <td>¥<%= room.room_fee %></td>
          <td><%= link_to '詳細はこちら', room_path(room) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/rooms/show.html.erb
<h2>施設詳細</h2>

<table>
  <tr>
    <th>施設画像</th>
    <td>
    <% if @room.room_image.present? %>
      <%= image_tag @room.room_image.url %>
    <% else %>
      <%= image_tag("default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png")%>
    <% end %>
    </td>
  </tr>
  <tr>
    <th>施設名</th>
    <td><%= @room.room_name %></td>
  </tr>
  <tr>
    <th>紹介文</th>
    <td><%= @room.room_introduction %></td>
  </tr>
  <tr>
    <th>宿泊料金</th>
    <td>¥<%= @room.room_fee %></td>
  </tr>
</table>

<p><%= link_to '予約', new_reservation_path(id: @room) %></p>
<%= link_to "戻る", :back %>